In [146]:
#New Juice 2 LinkedIn Data Analysis

In [147]:
import pandas as pd

In [148]:
import numpy as np

In [149]:
import seaborn as sns

In [150]:
Febdf = pd.read_csv('dux-soup-visit-data@2021-02-23 10h50.csv')

In [151]:
Febdf.head()

,id,VisitTime,Profile,SalesProfile,Picture,Degree,First Name,Middle Name,Last Name,Connections,...,CompanyWebsite,Email,Phone,IM,Twitter,Location,Industry,My Tags,My Notes,Unnamed: 24
0,id.187999202,2021/01/15 09:41:38,https://www.linkedin.com/in/philippaartus,https://www.linkedin.com/sales/people/ACwAAAs0...,https://media-exp1.licdn.com/dms/image/C5603AQ...,3,Philippa,,Artus,1340,...,https://www.moorwand.com,,,,,"London Area, United Kingdom",Financial Services,|🦆-default-invited,NaN,NaN
1,id.28086713,2021/01/15 09:42:50,https://www.linkedin.com/in/jappy-takhar-a754a59,https://www.linkedin.com/sales/people/ACwAAAGs...,https://media-exp1.licdn.com/dms/image/C5603AQ...,3,Jappy,,Takhar,1376,...,http://www.comitfs.com,,,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited,NaN,NaN
2,id.1310264,2021/01/15 09:43:39,https://www.linkedin.com/in/anjelikaklamp,https://www.linkedin.com/sales/people/ACwAAAAT...,,3,Anjelika,Klamp,Cfa,1069,...,http://www.igen-capital.com,,,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited,NaN,NaN
3,id.137682286,2021/01/15 09:44:55,https://www.linkedin.com/in/henry-arundel-2ba1...,https://www.linkedin.com/sales/people/ACwAAAg0...,https://media-exp1.licdn.com/dms/image/C5603AQ...,3,Henry,,Arundel,623,...,http://www.nobleinsurance.co.uk,,,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited,NaN,NaN
4,id.2726244,2021/01/15 09:46:20,https://www.linkedin.com/in/simon-freeman-830ab5,https://www.linkedin.com/sales/people/ACwAAAAp...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,3,Simon,,Freeman,515,...,,,,,snowbirdfinance,"Kingston upon Thames, England, United Kingdom",Financial Services,|🦆-default-invited,NaN,NaN

In [235]:
Febdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1332 entries, 0 to 1331
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              1332 non-null   object
 1   VisitTime       1332 non-null   datetime64[ns]
 2   Profile         1332 non-null   object
 3   SalesProfile    1332 non-null   object
 4   Picture         1332 non-null   object
 5   Degree          1332 non-null   object
 6   First Name      1332 non-null   object
 7   Middle Name     1332 non-null   object
 8   Last Name       1332 non-null   object
 9   Connections     1332 non-null   int64
 10  Summary         1332 non-null   object
 11  From            1332 non-null   object
 12  Title           1332 non-null   object
 13  Company         1332 non-null   object
 14  CompanyProfile  1332 non-null   object
 15  CompanyWebsite  1332 non-null   object
 16  Email           1332 non-null   object
 17  Phone           1332 non-null   object
 18  IM              1332 non-null   object
 19  Twitter         1332 non-null   object
 20  Location        1332 non-null   object
 21  Industry        1332 non-null   object
 22  My Tags         1303 non-null   object
 23  My Notes        0 non-null      float64
 24  Unnamed: 24     0 non-null      float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(21)
memory usage: 260.3+ KB

In [154]:
Febdf['VisitTime']=pd.to_datetime(Febdf['VisitTime'])

In [155]:
Febdf['VisitTime']

0      2021-01-15 09:41:38
1      2021-01-15 09:42:50
2      2021-01-15 09:43:39
3      2021-01-15 09:44:55
4      2021-01-15 09:46:20
               ...
1327   2021-02-22 11:02:07
1328   2021-02-22 11:03:20
1329   2021-02-22 11:04:44
1330   2021-02-22 11:06:01
1331   2021-02-22 11:07:11
Name: VisitTime, Length: 1332, dtype: datetime64[ns]

In [156]:
Febdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1332 entries, 0 to 1331
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              1332 non-null   object
 1   VisitTime       1332 non-null   datetime64[ns]
 2   Profile         1332 non-null   object
 3   SalesProfile    1332 non-null   object
 4   Picture         1332 non-null   object
 5   Degree          1332 non-null   object
 6   First Name      1332 non-null   object
 7   Middle Name     1332 non-null   object
 8   Last Name       1332 non-null   object
 9   Connections     1332 non-null   int64
 10  Summary         1332 non-null   object
 11  From            1332 non-null   object
 12  Title           1332 non-null   object
 13  Company         1332 non-null   object
 14  CompanyProfile  1332 non-null   object
 15  CompanyWebsite  1332 non-null   object
 16  Email           1332 non-null   object
 17  Phone           1332 non-null   object
 18  IM              1332 non-null   object
 19  Twitter         1332 non-null   object
 20  Location        1332 non-null   object
 21  Industry        1332 non-null   object
 22  My Tags         1303 non-null   object
 23  My Notes        0 non-null      float64
 24  Unnamed: 24     0 non-null      float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(21)
memory usage: 260.3+ KB

In [157]:
secondaudience=Febdf['VisitTime']>='2021-02-19 09:00:00'

In [158]:
secondaudience

0       False
1       False
2       False
3       False
4       False
        ...
1327     True
1328     True
1329     True
1330     True
1331     True
Name: VisitTime, Length: 1332, dtype: bool

In [159]:
Febdf[secondaudience]

,id,VisitTime,Profile,SalesProfile,Picture,Degree,First Name,Middle Name,Last Name,Connections,...,CompanyWebsite,Email,Phone,IM,Twitter,Location,Industry,My Tags,My Notes,Unnamed: 24
1214,id.1083385,2021-02-19 10:02:24,https://www.linkedin.com/in/michaelburling,https://www.linkedin.com/sales/people/ACwAAAAQ...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,3,Michael,,Burling,2413,...,https://www.lightbend.com,,,,burlomp,"Ascot, England, United Kingdom",Computer Software,NaN,NaN,NaN
1215,id.4023587,2021-02-19 10:03:36,https://www.linkedin.com/in/ivickers,https://www.linkedin.com/sales/people/ACwAAAA9...,,3,Ian,,Vickers,2049,...,http://www.metcloud.com,,,,,"West Midlands, England, United Kingdom",Information Technology and Services,NaN,NaN,NaN
1216,id.73546610,2021-02-19 10:04:32,https://www.linkedin.com/in/melissa-snover-842...,https://www.linkedin.com/sales/people/ACwAAARi...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,2,Melissa,,Snover,14434,...,https://get-nourished.com/,,,,,"West Midlands, England, United Kingdom",Food & Beverages,NaN,NaN,NaN
1217,id.27975143,2021-02-19 10:05:16,https://www.linkedin.com/in/peterbruch,https://www.linkedin.com/sales/people/ACwAAAGq...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,3,Peter,,Bruch,1640,...,http://aeaerospace.com,,,,aeaerospace,"West Midlands, England, United Kingdom",Aviation & Aerospace,NaN,NaN,NaN
1218,id.17512866,2021-02-19 10:06:20,https://www.linkedin.com/in/simoncrane144517,https://www.linkedin.com/sales/people/ACwAAAEL...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,2,Simon,,Crane,2265,...,,,,,,"Windsor, England, United Kingdom",Pharmaceuticals,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1327,id.139078819,2021-02-22 11:02:07,https://www.linkedin.com/in/pedrocarrajola,https://www.linkedin.com/sales/people/ACwAAAhK...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,3,Pedro,,Carrajola,1297,...,https://www.berkshirecloud.com,,,,pcarrajola,"Reading, England, United Kingdom",Information Technology and Services,|🦆-default-invited,NaN,NaN
1328,id.3517142,2021-02-22 11:03:20,https://www.linkedin.com/in/andrewwmoore65,https://www.linkedin.com/sales/people/ACwAAAA1...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,3,Andrew,,Moore,5006,...,http://www.uksol.co.uk,,,,solarmanmoore,"Farnham Common, England, United Kingdom",Renewables & Environment,|🦆-default-invited,NaN,NaN
1329,id.784625987,2021-02-22 11:04:44,https://www.linkedin.com/in/bhupesh-bector-b6b...,https://www.linkedin.com/sales/people/ACwAAC7E...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,3,Bhupesh,,Bector,894,...,,,,,,"Slough, England, United Kingdom",Food & Beverages,|🦆-default-invited,NaN,NaN
1330,id.47901181,2021-02-22 11:06:01,https://www.linkedin.com/in/daryn-parfitt-7110...,https://www.linkedin.com/sales/people/ACwAAALa...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,2,Daryn,,Parfitt,11724,...,http://heps360.com/,,,,,"West Midlands, England, United Kingdom",Construction,|🦆-default-invited,NaN,NaN
1331,id.2403842,2021-02-22 11:07:11,https://www.linkedin.com/in/nichutchins,https://www.linkedin.com/sales/people/ACwAAAAk...,,2,Nic,,Hutchins,1615,...,http://www.helmpartnering.com,,,,,"Windsor, England, United Kingdom",Information Technology and Services,|🦆-default-invited,NaN,NaN

In [160]:
secondlist=Febdf[secondaudience]

In [161]:
secondlist

,id,VisitTime,Profile,SalesProfile,Picture,Degree,First Name,Middle Name,Last Name,Connections,...,CompanyWebsite,Email,Phone,IM,Twitter,Location,Industry,My Tags,My Notes,Unnamed: 24
1214,id.1083385,2021-02-19 10:02:24,https://www.linkedin.com/in/michaelburling,https://www.linkedin.com/sales/people/ACwAAAAQ...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,3,Michael,,Burling,2413,...,https://www.lightbend.com,,,,burlomp,"Ascot, England, United Kingdom",Computer Software,NaN,NaN,NaN
1215,id.4023587,2021-02-19 10:03:36,https://www.linkedin.com/in/ivickers,https://www.linkedin.com/sales/people/ACwAAAA9...,,3,Ian,,Vickers,2049,...,http://www.metcloud.com,,,,,"West Midlands, England, United Kingdom",Information Technology and Services,NaN,NaN,NaN
1216,id.73546610,2021-02-19 10:04:32,https://www.linkedin.com/in/melissa-snover-842...,https://www.linkedin.com/sales/people/ACwAAARi...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,2,Melissa,,Snover,14434,...,https://get-nourished.com/,,,,,"West Midlands, England, United Kingdom",Food & Beverages,NaN,NaN,NaN
1217,id.27975143,2021-02-19 10:05:16,https://www.linkedin.com/in/peterbruch,https://www.linkedin.com/sales/people/ACwAAAGq...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,3,Peter,,Bruch,1640,...,http://aeaerospace.com,,,,aeaerospace,"West Midlands, England, United Kingdom",Aviation & Aerospace,NaN,NaN,NaN
1218,id.17512866,2021-02-19 10:06:20,https://www.linkedin.com/in/simoncrane144517,https://www.linkedin.com/sales/people/ACwAAAEL...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,2,Simon,,Crane,2265,...,,,,,,"Windsor, England, United Kingdom",Pharmaceuticals,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1327,id.139078819,2021-02-22 11:02:07,https://www.linkedin.com/in/pedrocarrajola,https://www.linkedin.com/sales/people/ACwAAAhK...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,3,Pedro,,Carrajola,1297,...,https://www.berkshirecloud.com,,,,pcarrajola,"Reading, England, United Kingdom",Information Technology and Services,|🦆-default-invited,NaN,NaN
1328,id.3517142,2021-02-22 11:03:20,https://www.linkedin.com/in/andrewwmoore65,https://www.linkedin.com/sales/people/ACwAAAA1...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,3,Andrew,,Moore,5006,...,http://www.uksol.co.uk,,,,solarmanmoore,"Farnham Common, England, United Kingdom",Renewables & Environment,|🦆-default-invited,NaN,NaN
1329,id.784625987,2021-02-22 11:04:44,https://www.linkedin.com/in/bhupesh-bector-b6b...,https://www.linkedin.com/sales/people/ACwAAC7E...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,3,Bhupesh,,Bector,894,...,,,,,,"Slough, England, United Kingdom",Food & Beverages,|🦆-default-invited,NaN,NaN
1330,id.47901181,2021-02-22 11:06:01,https://www.linkedin.com/in/daryn-parfitt-7110...,https://www.linkedin.com/sales/people/ACwAAALa...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,2,Daryn,,Parfitt,11724,...,http://heps360.com/,,,,,"West Midlands, England, United Kingdom",Construction,|🦆-default-invited,NaN,NaN
1331,id.2403842,2021-02-22 11:07:11,https://www.linkedin.com/in/nichutchins,https://www.linkedin.com/sales/people/ACwAAAAk...,,2,Nic,,Hutchins,1615,...,http://www.helmpartnering.com,,,,,"Windsor, England, United Kingdom",Information Technology and Services,|🦆-default-invited,NaN,NaN

In [162]:
secondlist.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 118 entries, 1214 to 1331
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              118 non-null    object
 1   VisitTime       118 non-null    datetime64[ns]
 2   Profile         118 non-null    object
 3   SalesProfile    118 non-null    object
 4   Picture         118 non-null    object
 5   Degree          118 non-null    object
 6   First Name      118 non-null    object
 7   Middle Name     118 non-null    object
 8   Last Name       118 non-null    object
 9   Connections     118 non-null    int64
 10  Summary         118 non-null    object
 11  From            118 non-null    object
 12  Title           118 non-null    object
 13  Company         118 non-null    object
 14  CompanyProfile  118 non-null    object
 15  CompanyWebsite  118 non-null    object
 16  Email           118 non-null    object
 17  Phone           118 non-null    object
 18  IM              118 non-null    object
 19  Twitter         118 non-null    object
 20  Location        118 non-null    object
 21  Industry        118 non-null    object
 22  My Tags         100 non-null    object
 23  My Notes        0 non-null      float64
 24  Unnamed: 24     0 non-null      float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(21)
memory usage: 24.0+ KB

In [163]:
secondlist.sample()

,id,VisitTime,Profile,SalesProfile,Picture,Degree,First Name,Middle Name,Last Name,Connections,...,CompanyWebsite,Email,Phone,IM,Twitter,Location,Industry,My Tags,My Notes,Unnamed: 24
1296,id.12687151,2021-02-22 10:14:57,https://www.linkedin.com/in/janegalsworthy,https://www.linkedin.com/sales/people/ACwAAADB...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,2,Jane,,Galsworthy,1983,...,https://oxin.co.uk/,,,,janegalsworthy,Greater Oxford Area,Professional Training & Coaching,|🦆-default-invited,NaN,NaN

In [166]:
df = pd.read_csv('dux-soup-visit-data@2021-03-16 13h33.csv')

In [167]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 868 entries, 0 to 867
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              868 non-null    object
 1   VisitTime       868 non-null    object
 2   Profile         868 non-null    object
 3   SalesProfile    868 non-null    object
 4   Picture         868 non-null    object
 5   Degree          868 non-null    int64
 6   First Name      868 non-null    object
 7   Middle Name     868 non-null    object
 8   Last Name       868 non-null    object
 9   Connections     868 non-null    int64
 10  Summary         868 non-null    object
 11  From            868 non-null    object
 12  Title           868 non-null    object
 13  Company         868 non-null    object
 14  CompanyProfile  868 non-null    object
 15  CompanyWebsite  868 non-null    object
 16  Email           868 non-null    object
 17  Phone           868 non-null    object
 18  IM              868 non-null    object
 19  Twitter         868 non-null    object
 20  Location        868 non-null    object
 21  Industry        868 non-null    object
 22  My Tags         851 non-null    object
 23  My Notes        0 non-null      float64
 24  Unnamed: 24     0 non-null      float64
dtypes: float64(2), int64(2), object(21)
memory usage: 169.7+ KB

In [168]:
df['VisitTime']=pd.to_datetime(df['VisitTime'])

In [169]:
df

,id,VisitTime,Profile,SalesProfile,Picture,Degree,First Name,Middle Name,Last Name,Connections,...,CompanyWebsite,Email,Phone,IM,Twitter,Location,Industry,My Tags,My Notes,Unnamed: 24
0,id.1083385,2021-02-23 12:08:04,https://www.linkedin.com/in/michaelburling,https://www.linkedin.com/sales/people/ACwAAAAQ...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,3,Michael,,Burling,2414,...,https://www.lightbend.com,,,,burlomp,"Ascot, England, United Kingdom",Computer Software,NaN,NaN,NaN
1,id.73546610,2021-02-23 12:09:16,https://www.linkedin.com/in/melissa-snover-842...,https://www.linkedin.com/sales/people/ACwAAARi...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,2,Melissa,,Snover,14531,...,https://get-nourished.com/,,,,,"West Midlands, England, United Kingdom",Food & Beverages,NaN,NaN,NaN
2,id.4023587,2021-02-23 12:10:11,https://www.linkedin.com/in/ivickers,https://www.linkedin.com/sales/people/ACwAAAA9...,,2,Ian,,Vickers,2060,...,http://www.metcloud.com,,,,,"West Midlands, England, United Kingdom",Information Technology and Services,NaN,NaN,NaN
3,id.17512866,2021-02-23 12:11:18,https://www.linkedin.com/in/simoncrane144517,https://www.linkedin.com/sales/people/ACwAAAEL...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,2,Simon,,Crane,2271,...,,,,,,"Windsor, England, United Kingdom",Pharmaceuticals,NaN,NaN,NaN
4,id.82776665,2021-02-23 12:12:24,https://www.linkedin.com/in/markinsley,https://www.linkedin.com/sales/people/ACwAAATv...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,2,Mark,,Insley,6196,...,http://www.ascotwm.com,,,,ascotwm,"Sunningdale, England, United Kingdom",Financial Services,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,id.61206813,2021-03-16 13:25:15,https://www.linkedin.com/in/mitul-gadhia-msc-7...,https://www.linkedin.com/sales/people/ACwAAAOl...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Mitul,,Gadhia,6771,...,,mitul.gadhia@whitegates.co.uk,07917765669,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|Sent Blog 1|sent blog 2|sen...,NaN,NaN
864,id.13027841,2021-03-16 13:26:35,https://www.linkedin.com/in/chris-northwood,https://www.linkedin.com/sales/people/ACwAAADG...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Chris,,Northwood,1564,...,https://www.dltapps.co.uk/,chris.northwood39@gmail.com,,,,United Kingdom,Financial Services,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN
865,id.6035529,2021-03-16 13:27:57,https://www.linkedin.com/in/david-hennah-9490302,https://www.linkedin.com/sales/people/ACwAAABc...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,David,,Hennah,4472,...,http://www.intellectdesign.com,davidhennah@hotmail.co.uk,+44 (0) 7962 012326,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|Sent Blog 1|sent blog 2|sen...,NaN,NaN
866,id.299626321,2021-03-16 13:29:57,https://www.linkedin.com/in/imran-hussain-a414...,https://www.linkedin.com/sales/people/ACwAABHb...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Imran,,Hussain,3793,...,,igmhussain@gmail.com,+44 7583 119756,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN
867,id.740585239,2021-03-16 13:31:17,https://www.linkedin.com/in/louis-kramer-50702...,https://www.linkedin.com/sales/people/ACwAACwk...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Louis,,Kramer,109,...,http://www.farazadinvest.com,louis.k@farazadinvest.com,,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN

In [236]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 868 entries, 0 to 867
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              868 non-null    object
 1   VisitTime       868 non-null    datetime64[ns]
 2   Profile         868 non-null    object
 3   SalesProfile    868 non-null    object
 4   Picture         868 non-null    object
 5   Degree          868 non-null    int64
 6   First Name      868 non-null    object
 7   Middle Name     868 non-null    object
 8   Last Name       868 non-null    object
 9   Connections     868 non-null    int64
 10  Summary         868 non-null    object
 11  From            868 non-null    object
 12  Title           868 non-null    object
 13  Company         868 non-null    object
 14  CompanyProfile  868 non-null    object
 15  CompanyWebsite  868 non-null    object
 16  Email           868 non-null    object
 17  Phone           868 non-null    object
 18  IM              868 non-null    object
 19  Twitter         868 non-null    object
 20  Location        868 non-null    object
 21  Industry        868 non-null    object
 22  My Tags         851 non-null    object
 23  My Notes        0 non-null      float64
 24  Unnamed: 24     0 non-null      float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(20)
memory usage: 169.7+ KB

In [207]:
dfall=pd.concat([secondlist,df],axis=0)

In [208]:
dfall

,id,VisitTime,Profile,SalesProfile,Picture,Degree,First Name,Middle Name,Last Name,Connections,...,CompanyWebsite,Email,Phone,IM,Twitter,Location,Industry,My Tags,My Notes,Unnamed: 24
1214,id.1083385,2021-02-19 10:02:24,https://www.linkedin.com/in/michaelburling,https://www.linkedin.com/sales/people/ACwAAAAQ...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,3,Michael,,Burling,2413,...,https://www.lightbend.com,,,,burlomp,"Ascot, England, United Kingdom",Computer Software,NaN,NaN,NaN
1215,id.4023587,2021-02-19 10:03:36,https://www.linkedin.com/in/ivickers,https://www.linkedin.com/sales/people/ACwAAAA9...,,3,Ian,,Vickers,2049,...,http://www.metcloud.com,,,,,"West Midlands, England, United Kingdom",Information Technology and Services,NaN,NaN,NaN
1216,id.73546610,2021-02-19 10:04:32,https://www.linkedin.com/in/melissa-snover-842...,https://www.linkedin.com/sales/people/ACwAAARi...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,2,Melissa,,Snover,14434,...,https://get-nourished.com/,,,,,"West Midlands, England, United Kingdom",Food & Beverages,NaN,NaN,NaN
1217,id.27975143,2021-02-19 10:05:16,https://www.linkedin.com/in/peterbruch,https://www.linkedin.com/sales/people/ACwAAAGq...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,3,Peter,,Bruch,1640,...,http://aeaerospace.com,,,,aeaerospace,"West Midlands, England, United Kingdom",Aviation & Aerospace,NaN,NaN,NaN
1218,id.17512866,2021-02-19 10:06:20,https://www.linkedin.com/in/simoncrane144517,https://www.linkedin.com/sales/people/ACwAAAEL...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,2,Simon,,Crane,2265,...,,,,,,"Windsor, England, United Kingdom",Pharmaceuticals,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,id.61206813,2021-03-16 13:25:15,https://www.linkedin.com/in/mitul-gadhia-msc-7...,https://www.linkedin.com/sales/people/ACwAAAOl...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Mitul,,Gadhia,6771,...,,mitul.gadhia@whitegates.co.uk,07917765669,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|Sent Blog 1|sent blog 2|sen...,NaN,NaN
864,id.13027841,2021-03-16 13:26:35,https://www.linkedin.com/in/chris-northwood,https://www.linkedin.com/sales/people/ACwAAADG...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Chris,,Northwood,1564,...,https://www.dltapps.co.uk/,chris.northwood39@gmail.com,,,,United Kingdom,Financial Services,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN
865,id.6035529,2021-03-16 13:27:57,https://www.linkedin.com/in/david-hennah-9490302,https://www.linkedin.com/sales/people/ACwAAABc...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,David,,Hennah,4472,...,http://www.intellectdesign.com,davidhennah@hotmail.co.uk,+44 (0) 7962 012326,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|Sent Blog 1|sent blog 2|sen...,NaN,NaN
866,id.299626321,2021-03-16 13:29:57,https://www.linkedin.com/in/imran-hussain-a414...,https://www.linkedin.com/sales/people/ACwAABHb...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Imran,,Hussain,3793,...,,igmhussain@gmail.com,+44 7583 119756,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN
867,id.740585239,2021-03-16 13:31:17,https://www.linkedin.com/in/louis-kramer-50702...,https://www.linkedin.com/sales/people/ACwAACwk...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Louis,,Kramer,109,...,http://www.farazadinvest.com,louis.k@farazadinvest.com,,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN

In [211]:
First=dfall['Degree']==1

In [212]:
dfall[First]

,id,VisitTime,Profile,SalesProfile,Picture,Degree,First Name,Middle Name,Last Name,Connections,...,CompanyWebsite,Email,Phone,IM,Twitter,Location,Industry,My Tags,My Notes,Unnamed: 24
517,id.18211192,2021-03-08 11:56:55,https://www.linkedin.com/in/davidwoakesrsl,https://www.linkedin.com/sales/people/ACwAAAEV...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,1,David,Woakes Ccwp And Sow,Management,6960,...,http://www.advantagegroup.co.uk,david.woakes@advantagegroup.co.uk,07741 644767,,JonLee_Aero,"West Midlands, England, United Kingdom",Staffing and Recruiting,|🦆-default-invited|conversation,NaN,NaN
768,id.625383525,2021-03-16 10:54:13,https://www.linkedin.com/in/gareth-twist-91953...,https://www.linkedin.com/sales/people/ACwAACVG...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Gareth,,Twist,4421,...,https://www.coindirect.com,twistgareth@gmail.com,,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|Sent Blog 1|sent blog 2|sen...,NaN,NaN
769,id.14573889,2021-03-16 10:55:25,https://www.linkedin.com/in/akeelkazmi-executi...,https://www.linkedin.com/sales/people/ACwAAADe...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Akeel,,Kazmi,4578,...,http://www.citydefend.com,akeel@upskillpd.co.uk,07956584610,,,"London Area, United Kingdom",Financial Services,|🦆-default-invited|Sent Blog 1|sent blog 2|sen...,NaN,NaN
770,id.109825787,2021-03-16 10:56:48,https://www.linkedin.com/in/daniel-goggin-70b9...,https://www.linkedin.com/sales/people/ACwAAAaL...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Daniel,,Goggin,2788,...,http://www.adsenmoore.co.uk,daniel_goggin@hotmail.co.uk,+44 (0) 7944 623 646,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN
771,id.112118175,2021-03-16 10:58:09,https://www.linkedin.com/in/malcolm-dixon-2536...,https://www.linkedin.com/sales/people/ACwAAAau...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Malcolm,,Dixon,1710,...,https://www.whiskyinvestmentpartners.com/,malcolmjohndixon@gmail.com,+44 7709 394301,,,"London Area, United Kingdom",Financial Services,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,id.61206813,2021-03-16 13:25:15,https://www.linkedin.com/in/mitul-gadhia-msc-7...,https://www.linkedin.com/sales/people/ACwAAAOl...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Mitul,,Gadhia,6771,...,,mitul.gadhia@whitegates.co.uk,07917765669,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|Sent Blog 1|sent blog 2|sen...,NaN,NaN
864,id.13027841,2021-03-16 13:26:35,https://www.linkedin.com/in/chris-northwood,https://www.linkedin.com/sales/people/ACwAAADG...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Chris,,Northwood,1564,...,https://www.dltapps.co.uk/,chris.northwood39@gmail.com,,,,United Kingdom,Financial Services,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN
865,id.6035529,2021-03-16 13:27:57,https://www.linkedin.com/in/david-hennah-9490302,https://www.linkedin.com/sales/people/ACwAAABc...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,David,,Hennah,4472,...,http://www.intellectdesign.com,davidhennah@hotmail.co.uk,+44 (0) 7962 012326,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|Sent Blog 1|sent blog 2|sen...,NaN,NaN
866,id.299626321,2021-03-16 13:29:57,https://www.linkedin.com/in/imran-hussain-a414...,https://www.linkedin.com/sales/people/ACwAABHb...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Imran,,Hussain,3793,...,,igmhussain@gmail.com,+44 7583 119756,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN
867,id.740585239,2021-03-16 13:31:17,https://www.linkedin.com/in/louis-kramer-50702...,https://www.linkedin.com/sales/people/ACwAACwk...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Louis,,Kramer,109,...,http://www.farazadinvest.com,louis.k@farazadinvest.com,,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN

In [234]:
first=dfall[First]

In [227]:
first

,id,VisitTime,Profile,SalesProfile,Picture,Degree,First Name,Middle Name,Last Name,Connections,...,CompanyWebsite,Email,Phone,IM,Twitter,Location,Industry,My Tags,My Notes,Unnamed: 24
517,id.18211192,2021-03-08 11:56:55,https://www.linkedin.com/in/davidwoakesrsl,https://www.linkedin.com/sales/people/ACwAAAEV...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,1,David,Woakes Ccwp And Sow,Management,6960,...,http://www.advantagegroup.co.uk,david.woakes@advantagegroup.co.uk,07741 644767,,JonLee_Aero,"West Midlands, England, United Kingdom",Staffing and Recruiting,|🦆-default-invited|conversation,NaN,NaN
768,id.625383525,2021-03-16 10:54:13,https://www.linkedin.com/in/gareth-twist-91953...,https://www.linkedin.com/sales/people/ACwAACVG...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Gareth,,Twist,4421,...,https://www.coindirect.com,twistgareth@gmail.com,,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|Sent Blog 1|sent blog 2|sen...,NaN,NaN
769,id.14573889,2021-03-16 10:55:25,https://www.linkedin.com/in/akeelkazmi-executi...,https://www.linkedin.com/sales/people/ACwAAADe...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Akeel,,Kazmi,4578,...,http://www.citydefend.com,akeel@upskillpd.co.uk,07956584610,,,"London Area, United Kingdom",Financial Services,|🦆-default-invited|Sent Blog 1|sent blog 2|sen...,NaN,NaN
770,id.109825787,2021-03-16 10:56:48,https://www.linkedin.com/in/daniel-goggin-70b9...,https://www.linkedin.com/sales/people/ACwAAAaL...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Daniel,,Goggin,2788,...,http://www.adsenmoore.co.uk,daniel_goggin@hotmail.co.uk,+44 (0) 7944 623 646,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN
771,id.112118175,2021-03-16 10:58:09,https://www.linkedin.com/in/malcolm-dixon-2536...,https://www.linkedin.com/sales/people/ACwAAAau...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Malcolm,,Dixon,1710,...,https://www.whiskyinvestmentpartners.com/,malcolmjohndixon@gmail.com,+44 7709 394301,,,"London Area, United Kingdom",Financial Services,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,id.61206813,2021-03-16 13:25:15,https://www.linkedin.com/in/mitul-gadhia-msc-7...,https://www.linkedin.com/sales/people/ACwAAAOl...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Mitul,,Gadhia,6771,...,,mitul.gadhia@whitegates.co.uk,07917765669,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|Sent Blog 1|sent blog 2|sen...,NaN,NaN
864,id.13027841,2021-03-16 13:26:35,https://www.linkedin.com/in/chris-northwood,https://www.linkedin.com/sales/people/ACwAAADG...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Chris,,Northwood,1564,...,https://www.dltapps.co.uk/,chris.northwood39@gmail.com,,,,United Kingdom,Financial Services,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN
865,id.6035529,2021-03-16 13:27:57,https://www.linkedin.com/in/david-hennah-9490302,https://www.linkedin.com/sales/people/ACwAAABc...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,David,,Hennah,4472,...,http://www.intellectdesign.com,davidhennah@hotmail.co.uk,+44 (0) 7962 012326,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|Sent Blog 1|sent blog 2|sen...,NaN,NaN
866,id.299626321,2021-03-16 13:29:57,https://www.linkedin.com/in/imran-hussain-a414...,https://www.linkedin.com/sales/people/ACwAABHb...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Imran,,Hussain,3793,...,,igmhussain@gmail.com,+44 7583 119756,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN
867,id.740585239,2021-03-16 13:31:17,https://www.linkedin.com/in/louis-kramer-50702...,https://www.linkedin.com/sales/people/ACwAACwk...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Louis,,Kramer,109,...,http://www.farazadinvest.com,louis.k@farazadinvest.com,,,,"London, England, United Kingdom",Financial Services,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN

In [214]:
first.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 101 entries, 517 to 867
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              101 non-null    object
 1   VisitTime       101 non-null    datetime64[ns]
 2   Profile         101 non-null    object
 3   SalesProfile    101 non-null    object
 4   Picture         101 non-null    object
 5   Degree          101 non-null    object
 6   First Name      101 non-null    object
 7   Middle Name     101 non-null    object
 8   Last Name       101 non-null    object
 9   Connections     101 non-null    int64
 10  Summary         101 non-null    object
 11  From            101 non-null    object
 12  Title           101 non-null    object
 13  Company         101 non-null    object
 14  CompanyProfile  101 non-null    object
 15  CompanyWebsite  101 non-null    object
 16  Email           101 non-null    object
 17  Phone           101 non-null    object
 18  IM              101 non-null    object
 19  Twitter         101 non-null    object
 20  Location        101 non-null    object
 21  Industry        101 non-null    object
 22  My Tags         101 non-null    object
 23  My Notes        0 non-null      float64
 24  Unnamed: 24     0 non-null      float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(21)
memory usage: 20.5+ KB

In [223]:
citynumbers=first.groupby('Location')['Degree'] \
                             .count() \
                             .reset_index(name='count') \
                             .sort_values(['count'], ascending=False) \
                             .head(20)

In [229]:
citynumbers

                                   Location  count
4           London, England, United Kingdom     79
3               London Area, United Kingdom     10
8                            United Kingdom      3
0   City of London, England, United Kingdom      1
1          Enfield, England, United Kingdom      1
2                   Greater Portsmouth Area      1
5          Romford, England, United Kingdom      1
6    South Croydon, England, United Kingdom      1
7     St. Leonards, England, United Kingdom      1
9         Waterloo, England, United Kingdom      1
10         Wembley, England, United Kingdom      1
11   West Midlands, England, United Kingdom      1

In [225]:
industry=first.groupby('Industry')['Degree'] \
                             .count() \
                             .reset_index(name='count') \
                             .sort_values(['count'], ascending=False) \
                             .head(10)

In [228]:
industry

                              Industry  count
1                   Financial Services     93
0  Electrical/Electronic Manufacturing      7
2              Staffing and Recruiting      1

In [219]:
company=first.groupby('Company')['Degree'] \
                             .count() \
                             .reset_index(name='count') \
                             .sort_values(['count'], ascending=False) \
                             .head(5)

In [230]:
elec=first['Industry']=='Electrical/Electronic Manufacturing'

In [233]:
first[elec]

,id,VisitTime,Profile,SalesProfile,Picture,Degree,First Name,Middle Name,Last Name,Connections,...,CompanyWebsite,Email,Phone,IM,Twitter,Location,Industry,My Tags,My Notes,Unnamed: 24
796,id.76463537,2021-03-16 11:37:50,https://www.linkedin.com/in/sunday-ogar-89573521,https://www.linkedin.com/sales/people/ACwAAASO...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Sunday,,Ogar,4072,...,http://www.ogartechnology.com/,sales@ogartechnology.com,+448432897943,ogarconsulting2006,ogarconsulting,"Waterloo, England, United Kingdom",Electrical/Electronic Manufacturing,|🦆-default-invited|Sent Blog 1|sent case study,NaN,NaN
800,id.29597819,2021-03-16 11:43:16,https://www.linkedin.com/in/ian-townsend-44bab49,https://www.linkedin.com/sales/people/ACwAAAHD...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Ian,,Townsend,299,...,https://cmselectra.com/uk/,ian@cmselectra.com,,,,"London, England, United Kingdom",Electrical/Electronic Manufacturing,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN
829,id.67076676,2021-03-16 12:33:24,https://www.linkedin.com/in/gregg-barnes-6305691a,https://www.linkedin.com/sales/people/ACwAAAP_...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Gregg,,Barnes,2029,...,,gbarnes@eliteelectrical.co.uk,07887 946607,,,"London, England, United Kingdom",Electrical/Electronic Manufacturing,|🦆-default-invited|sent case study,NaN,NaN
838,id.630114461,2021-03-16 12:45:36,https://www.linkedin.com/in/jack-pleavin-6a503...,https://www.linkedin.com/sales/people/ACwAACWO...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Jack,,Pleavin,3419,...,http://www.pleavinpower.co.uk,jack@pleavinpower.co.uk,0800 689 4803,,,"London, England, United Kingdom",Electrical/Electronic Manufacturing,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN
847,id.83431903,2021-03-16 12:58:30,https://www.linkedin.com/in/muhammed-najmul-i-...,https://www.linkedin.com/sales/people/ACwAAAT5...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Muhammed,,Islam,490,...,http://www.duronic.com,,,,,"Romford, England, United Kingdom",Electrical/Electronic Manufacturing,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN
856,id.192815481,2021-03-16 13:15:44,https://www.linkedin.com/in/nick-king-0496a754,https://www.linkedin.com/sales/people/ACwAAAt-...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Nick,,King,3767,...,http://www.interface-manufacturing.com,nick.king@interface-manufacturing.com,07792741697,,,"St. Leonards, England, United Kingdom",Electrical/Electronic Manufacturing,|🦆-default-invited|sent blog 2|sent case study,NaN,NaN
857,id.474681147,2021-03-16 13:17:06,https://www.linkedin.com/in/ludvik-jaros,https://www.linkedin.com/sales/people/ACwAABxL...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Ludvík,,Jaroš,294,...,http://freebike.com/,ljaros@seznam.cz,,,,"London, England, United Kingdom",Electrical/Electronic Manufacturing,|🦆-default-invited|Sent Blog 1|sent blog 2|sen...,NaN,NaN

In [220]:
company

                                    Company  count
0            13D Global Strategy & Research      1
64                                     Laka      1
74  NATIONAL BANK OF KUWAIT INTERNATION PLC      1
73                      My Social Assistant      1
72                         Moneta Global FX      1

In [221]:
title=first.groupby('Title')['Degree'] \
                             .count() \
                             .reset_index(name='count') \
                             .sort_values(['count'], ascending=False) \
                             .head(5)

In [222]:
title

                               Title  count
40                 Managing Director     31
18  Director Of Business Development      5
26                           Founder      4
14                          Director      3
0                       Board Member      2

In [185]:
first['Title']=='Director of Business Development'

Series([], Name: Title, dtype: bool)

In [186]:
DBD=first['Title']=='Director Of Business Development'

In [187]:
dbd=first[DBD]

In [188]:
dbd.count()

id                0
VisitTime         0
Profile           0
SalesProfile      0
Picture           0
Degree            0
First Name        0
Middle Name       0
Last Name         0
Connections       0
Summary           0
From              0
Title             0
Company           0
CompanyProfile    0
CompanyWebsite    0
Email             0
Phone             0
IM                0
Twitter           0
Location          0
Industry          0
My Tags           0
My Notes          0
Unnamed: 24       0
dtype: int64

In [189]:
first['Title']=='Managing Director'

Series([], Name: Title, dtype: bool)

In [190]:
MD=first['Title']=='Managing Director'

In [191]:
MD

Series([], Name: Title, dtype: bool)

In [192]:
md=first[MD]

In [193]:
md.groupby('Title')['Degree'].count()

Series([], Name: Degree, dtype: int64)

In [194]:
md.count()

id                0
VisitTime         0
Profile           0
SalesProfile      0
Picture           0
Degree            0
First Name        0
Middle Name       0
Last Name         0
Connections       0
Summary           0
From              0
Title             0
Company           0
CompanyProfile    0
CompanyWebsite    0
Email             0
Phone             0
IM                0
Twitter           0
Location          0
Industry          0
My Tags           0
My Notes          0
Unnamed: 24       0
dtype: int64

In [195]:
first['Title']=='Marketing Director'

Series([], Name: Title, dtype: bool)

In [196]:
MarD=first['Title']=='Marketing Director'

In [197]:
Mark=first[MarD]

In [198]:
Mark.count()

id                0
VisitTime         0
Profile           0
SalesProfile      0
Picture           0
Degree            0
First Name        0
Middle Name       0
Last Name         0
Connections       0
Summary           0
From              0
Title             0
Company           0
CompanyProfile    0
CompanyWebsite    0
Email             0
Phone             0
IM                0
Twitter           0
Location          0
Industry          0
My Tags           0
My Notes          0
Unnamed: 24       0
dtype: int64

In [199]:
first['Title']=='Marketing Manager'

Series([], Name: Title, dtype: bool)

In [200]:
MarM=first['Title']=='Marketing Manager'

In [201]:
MM=first[MarM]

In [202]:
MM.count()

id                0
VisitTime         0
Profile           0
SalesProfile      0
Picture           0
Degree            0
First Name        0
Middle Name       0
Last Name         0
Connections       0
Summary           0
From              0
Title             0
Company           0
CompanyProfile    0
CompanyWebsite    0
Email             0
Phone             0
IM                0
Twitter           0
Location          0
Industry          0
My Tags           0
My Notes          0
Unnamed: 24       0
dtype: int64

In [203]:
first['Title']=='Sales Director'

Series([], Name: Title, dtype: bool)

In [204]:
sd=first['Title']=='Sales Director'

In [205]:
SD=first[sd]

In [206]:
SD.count()

id                0
VisitTime         0
Profile           0
SalesProfile      0
Picture           0
Degree            0
First Name        0
Middle Name       0
Last Name         0
Connections       0
Summary           0
From              0
Title             0
Company           0
CompanyProfile    0
CompanyWebsite    0
Email             0
Phone             0
IM                0
Twitter           0
Location          0
Industry          0
My Tags           0
My Notes          0
Unnamed: 24       0
dtype: int64